// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjauwjcsfqwyrriuacqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqYXV3amNzZnF3eXJyaXVhY3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTcxNjksImV4cCI6MjA2NTg5MzE2OX0.DztMTOFrSaWZj3h2GMgSTiDxttUYPBL58YuYqX7NANk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);